### ISSUE TITLE
Eprof or Epro?

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/cea-toolbox-for-arcgis-manual#4]
Final electricity in industrial processes is abbreviated in the `Hourly Values` as `Epro_kWh`, while the same definition in the `Yearly Values` is written as `Eprof_MWhyr`, so shouldn’t we fix it to either `Epro` or `Eprof`?

**Comment by JIMENOFONSECA** [comment]
i will go for Eprof, f means final... small change, it goes in the master branch

**Comment by JIMENOFONSECA** [comment]
fixed i nthe master branch
